### ISSUE TITLE
JSON Errors

### ISSUE THREAD

**Issue by seajaysec** [mikewilks/simple-pastebin-monitor#7]
After installing Requests I am receiving this error, which seems to indicate the page being requested isn't returning content in the proper JSON format - or perhaps just as HTML.

```
Starting a loop
Traceback (most recent call last):
  File "simple-pb-monitor.py", line 24, in <module>
    parsed_json = r.json()
  File "/usr/local/anaconda3/envs/py36/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/anaconda3/envs/py36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/anaconda3/envs/py36/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/anaconda3/envs/py36/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by seajaysec** [comment]
Ah, Pastebin updated the API URL. Line 18 should read:

```
    r = requests.get("https://scrape.pastebin.com/api_scraping.php?limit=100")
```

I'll submit a pull req in a little bit.

**Comment by mikewilks** [comment]
Took me a while but I have fixed this
